version: '3.6'
services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://localhost:9080'
        gitlab_rails['gitlab_shell_ssh_port'] = 9022
    ports:
      - '9080:9080'
      - '9043:9043'
      - '9022:9022'
    volumes:
      - D:/Space/software/docker-data/gitlab/config:/etc/gitlab
      - D:/Space/software/docker-data/gitlab/logs:/var/log/gitlab
      - D:/Space/software/docker-data/gitlab/data:/var/opt/gitlab
    shm_size: '256m'

  jenkins:
    image: 'jenkins/jenkins:lts-jdk17'
    container_name: jenkins
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '9020:8080'
      - '9021:50000'
    volumes:
      - D:/Space/software/docker-data/jenkins/jenkins_home:/var/jenkins_home
      - D:/Space/software/docker-data/jenkins/docker.sock:/var/run/docker.sock
      - D:/Space/software/docker-data/jenkins/docker:/usr/bin/docker



  


